export const FETCH_QUIZZES = "FETCH_QUIZZES";
export const UPDATE_QUIZ = "UPDATE_QUIZ";
export const NEW_QUIZ_ADDED = "NEW_QUIZ_ADDED";
export const GET_CURRENT_QUIZID = "GET_CURRENT_QUIZID";
export const FETCH_USER = "FETCH_USER";
